# This links the page index of the stackedwidget_experiment with the experiment names
experiments : {
    0: 'transmission',
    1: 'excitation_emission',
    2: 'decay'
}

# Instruments needed for each experiment
instruments : {
    'transmission': [ 'xystage', 'spectrometer' ],
    'excitation_emission': [ 'xystage', 'spectrometer','laser','shuttercontrol','powermeter'],
    'decay': [ 'xystage','laser','shuttercontrol', 'digitizer']
}

# Lists all the widgets per experiment
widgets : {
    'transmission': {
        'widget_file_transmission': '',
        'widget_xystage_transmission': 'xystage',
        'widget_xystageplot_transmission': 'xystage',
        'widget_spectrometer_transmission': 'spectrometer',
        'widget_spectrometerplot_transmission': 'spectrometer'
    },
    'excitation_emission': {
        'widget_file_excitation_emission': '',
        'widget_xystage_excitation_emission': 'xystage',
        'widget_xystageplot_excitation_emission' : 'xystage',
        'widget_spectrometer_excitation_emission': 'spectrometer',
        'widget_spectrometerplot_excitation_emission': 'spectrometer',
        'widget_powermeter_excitation_emission': 'powermeter',
        'widget_powermeterplot_excitation_emission': 'powermeter',
        'widget_laser_excitation_emission': 'laser',
        'widget_shuttercontrol_excitation_emission': 'shuttercontrol'
    },
    'decay': {
        'widget_file_decay': '',
        'widget_xystage_decay': 'xystage',
        'widget_xystageplot_decay': 'xystage',
        'widget_digitizer_decay': 'digitizer',
        'widget_digitizerplot_decay': 'digitizer',
        'widget_laser_decay': 'laser',
        'widget_shuttercontrol_decay': 'shuttercontrol'
    }
}
# Gui settings for the alignment and set experiment states
instrument_pages: {
    'align': {
        'page': 1,
        'preffered': 'page_alignment',
        'ignored': 'page_experiment',
        'text_button': 'Set Experiment',
        'enable_start': False,
        'beamsplitter_calibration': False,
        'text_button_beamsplitter': 'new beamsplitter calibration, go to set experiment'
    },
    'setExperiment': {
        'page': 0,
        'preffered': 'page_experiment',
        'ignored': 'page_alignment',
        'text_button': 'Alignment',
        'enable_start': True,
        'beamsplitter_calibration': True,
        'text_button_beamsplitter': 'new beamsplitter calibration'
    }
}
# Position settings for the different substrates
substrates: {
    # borofloat 50X50
    50X50 mm (Borofloat): {
        x_lamp: 10,          # x position when avantes lamp lightsource is centered on corner of sampleholder
        y_lamp: -4.7,        # y position when avantes lamp lightsource is centered on corner of sampleholder
        x_laser: 12,         # x position when avantes laser lightsource is centered on corner of sampleholder
        y_laser: 87,         # y position when avantes laser lightsource is centered on corner of sampleholder
        whse: 51,            # width holder sample edge
        hhse: 51,            # height holder sample edge
        ws: 48,              # width sample usable
        hs: 48,              # height sample usable
        dfhx: 6.8,           # distance from start of sample to side holder x
        dfhy: 4.7,           # distance from start of sample to side holder y
    },
    44X44 mm (Quartz): {
        name: 'Quartz 44 x 44 mm',
        x_lamp: 10,          # x position when avantes lamp lightsource is centered on corner of sampleholder
        y_lamp: -4.7,        # y position when avantes lamp lightsource is centered on corner of sampleholder
        x_laser: 12,         # x position when avantes laser lightsource is centered on corner of sampleholder
        y_laser: 87,         # y position when avantes laser lightsource is centered on corner of sampleholder
        whse: 45,            # width holder sample edge
        hhse: 45,            # height holder sample edge
        ws: 42,              # width sample usable
        hs: 42,              # height sample usable
        dfhx: 5,             # distance from start of sample to side holder x
        dfhy: 3.5,           # distance from start of sample to side holder y

    },
    22X22 mm (Quartz small): {
        name: 'Quartz 22 x 22 mm',
        x_lamp: 10,          # x position when avantes lamp lightsource is centered on corner of sampleholder
        y_lamp: -4.7,        # y position when avantes lamp lightsource is centered on corner of sampleholder
        x_laser: 12,         # x position when avantes laser lightsource is centered on corner of sampleholder
        y_laser: 87,         # y position when avantes laser lightsource is centered on corner of sampleholder
        whse: 26,            # width holder sample edge
        hhse: 26,            # height holder sample edge
        ws: 23,              # width sample usable
        hs: 23,              # height sample usable
        dfhx: 52.5,          # distance from start of sample to side holder x
        dfhy: 3.5,           # distance from start of sample to side holder y
    }
}
