# This links the page index of the stackedwidget_experiment with the experiment names
experiments : {
    0: 'transmission',
    1: 'excitation_emission',
    2: 'decay'
}

# Instruments needed for each experiment
instruments : {
    'transmission': [ 'xystage', 'spectrometer' ],
    'excitation_emission': [ 'xystage', 'spectrometer','laser','shuttercontrol','powermeter'],
    'decay': [ 'xystage','laser','shuttercontrol', 'ditigitzer']
}

# Lists all the widgets per experiment
widgets : {
    'transmission': {
        'widget_file_transmission': '',
        'widget_xystage_transmission': 'xystage',
        'widget_xystageplot_transmission': 'xystage',
        'widget_spectrometer_transmission': 'spectrometer',
        'widget_spectrometerplot_transmission': 'spectrometer'
    },
    'excitation_emission': {
        'widget_file_excitation_emission': '',
        'widget_xystage_excitation_emission': 'xystage',
        'widget_xystageplot_excitation_emission' : 'xystage',
        'widget_spectrometer_excitation_emission': 'spectrometer',
        'widget_spectrometerplot_excitation_emission': 'spectrometer',
        'widget_powermeter_excitation_emission': 'powermeter',
        'widget_powermeterplot_excitation_emission': 'powermeter',
        'widget_laser_excitation_emission': 'laser',
        'widget_shuttercontrol_excitation_emission': 'shuttercontrol'
    },
    'decay': {
        'widget_file_decay': '',
        'widget_xystage_decay': 'xystage',
        'widget_xystageplot_decay': 'xystage',
        'widget_digitizer_decay': 'digitizer',
        'widget_digitizerplot_decay': 'digitizer',
        'widget_laser_decay': 'laser',
        'widget_shuttercontrol_decay': 'shuttercontrol'
    }
}
# Gui settings for the alignment and set experiment states
instrument_pages: {
    'align': {
        'page': 1,
        'preffered': 'page_alignment',
        'ignored': 'page_experiment',
        'text_button': 'Set Experiment',
        'enable_start': False
    },
    'setExperiment': {
        'page': 0,
        'preffered': 'page_experiment',
        'ignored': 'page_alignment',
        'text_button': 'Alignment',
        'enable_start': True
    }
}
# Position settings for the different substrates
substrates: {
    # borofloat 50X50
    0: {
        x_start_transmission: 14,               # left upper corner position x (same for all experiments)
        x_start_excitation_emission: 14,        # left upper corner position y transmission measurements
        x_start_decay: 14,                      # left upper corner position y transmission measurements
        y_start_transmission: 15,               # left upper corner position y transmission measurements
        y_start_excitation_emission: 103,     # left upper corner position y EE measurements
        y_start_decay: 103,                   # left upper corner position y decay measurements
        whse: 51,                               # width holder sample edge
        hhse: 51,                               # height holder sample edge
        ws: 47,                                 # width sample usable
        hs: 47,                                 # height sample usable
        dfhx: 6.8,                              # distance from start of sample to side holder x
        dfhy: 4.7,                              # distance from start of sample to side holder y
        lightsource_x_transmission: 9,          # lightsource x position transmission
        lightsource_x_excitation_emission: 9,   # lightsource x position excitation emission
        lightsource_x_decay: 9,                 # lightsource x position excitation emission
        lightsource_y_transmission: 14,         # lightsource y position transmission
        lightsource_y_excitation_emission: 99,  # lightsource y position excitation emission
        lightsource_y_decay: 99                 # lightsource y position decay
    },
    1: {
        x_start_transmission: 14,               # left upper corner position x (same for all experiments)
        x_start_excitation_emission: 14,        # left upper corner position y transmission measurements
        x_start_decay: 14,                      # left upper corner position y transmission measurements
        y_start_transmission: 15,               # left upper corner position y transmission measurements
        y_start_excitation_emission: 103,       # left upper corner position y EE measurements
        y_start_decay: 103,                     # left upper corner position y decay measurements
        whse: 44,                               # width holder sample edge
        hhse: 44,                               # height holder sample edge
        ws: 42,                                 # width sample usable
        hs: 42,                                 # height sample usable
        dfhx: 6.8,                              # distance from start of sample to side holder x
        dfhy: 4.7,                              # distance from start of sample to side holder y
        lightsource_x_transmission: 9,          # lightsource x position transmission
        lightsource_x_excitation_emission: 9,   # lightsource x position excitation emission
        lightsource_x_decay: 9,                 # lightsource x position excitation emission
        lightsource_y_transmission: 14,         # lightsource y position transmission
        lightsource_y_excitation_emission: 99,  # lightsource y position excitation emission
        lightsource_y_decay: 99                 # lightsource y position decay
    },
    2: {
        x_start_transmission: 14,               # left upper corner position x (same for all experiments)
        x_start_excitation_emission: 14,        # left upper corner position y transmission measurements
        x_start_decay: 14,                      # left upper corner position y transmission measurements
        y_start_transmission: 15,               # left upper corner position y transmission measurements
        y_start_excitation_emission: 102.5,     # left upper corner position y EE measurements
        y_start_decay: 102.5,                   # left upper corner position y decay measurements
        whse: 25,                               # width holder sample edge
        hhse: 25,                               # height holder sample edge
        ws: 22,                                 # width sample usable
        hs: 22,                                 # height sample usable
        dfhx: 6.8,                              # distance from start of sample to side holder x
        dfhy: 4.7,                              # distance from start of sample to side holder y
        lightsource_x_transmission: 9,          # lightsource x position transmission
        lightsource_x_excitation_emission: 9,   # lightsource x position excitation emission
        lightsource_x_decay: 9,                 # lightsource x position excitation emission
        lightsource_y_transmission: 14,         # lightsource y position transmission
        lightsource_y_excitation_emission: 99,  # lightsource y position excitation emission
        lightsource_y_decay: 99                 # lightsource y position decay
    }

}

# Laser dictionary for parsing energylevel setting
laser: {
           0: 'Max',
           1: 'Adjust'
}