excitation_emission:
  widget_file_excitation_emission:
    lineEdit_directory: ''
    lineEdit_sample: ''
    plainTextEdit_comments: ''
  widget_laser_excitation_emission:
    doubleSpinBox_wavelength_start: 0.0
    doubleSpinBox_wavelength_step: 0.0
    doubleSpinBox_wavelength_stop: 0.0
    spinBox: 0
  widget_powermeter_excitation_emission:
    doubleSpinBox_integrationtime: 0.0
  widget_shuttercontrol_excitation_emission: {}
  widget_spectrometer_excitation_emission:
    doubleSpinBox_averageing_alignment: 0.0
    doubleSpinBox_averageing_experiment: 0.0
    doubleSpinBox_integration_time_alignment: 0.0
    doubleSpinBox_integration_time_experiment: 0.0
  widget_xystage_excitation_emission:
    doubleSpinBox_x: 0.0
    doubleSpinBox_x_start: 0.0
    doubleSpinBox_x_stop: 0.0
    doubleSpinBox_y: 0.0
    doubleSpinBox_y_start: 0.0
    doubleSpinBox_y_stop: 0.0
    spinBox_x_num: 0
    spinBox_y_num: 0
transmission:
  widget_file_transmission:
    checkBox_append_file: false
    comboBox_substrate: 0
    lineEdit_appendfile: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY/2106281727_Newsample.hdf5
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: BK666
    plainTextEdit_comments: 'The number of the beast '
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 400
    spinBox_integration_time_experiment: 1000
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 30.0
    doubleSpinBox_y: 30.0
    spinBox_x_num: 3
    spinBox_x_off_left: 5
    spinBox_x_off_right: 9
    spinBox_y_num: 3
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
