decay:
  widget_digitizer_decay:
    listWidget_channels_alignment: []
    listWidget_channels_experiment: []
    spinBox_integration_time_alignment: 1000
    spinBox_integration_time_experiment: 1000000
    spinBox_number_pulses_experiment: 1
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
  widget_file_decay:
    comboBox_substrate: 44X44 mm (Quartz)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_filter: BLP01-405R-25
    lineEdit_sample: B13
    plainTextEdit_comments: "Small dot with two adjustable apertures \nPMT at 2000V\n"
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 373
    spinBox_wavelength_start: 300
    spinBox_wavelength_step: 10
    spinBox_wavelength_stop: 389
  widget_shuttercontrol_decay:
    checkBox: false
  widget_xystage_decay:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 40.0
    doubleSpinBox_y: 90.0
    spinBox_x_num: 5
    spinBox_x_off_left: 10
    spinBox_x_off_right: 10
    spinBox_y_num: 5
    spinBox_y_off_bottom: 10
    spinBox_y_off_top: 10
excitation_emission:
  widget_file_excitation_emission:
    comboBox_substrate: 44X44 mm (Quartz)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_filter: BLP01-405R-25
    lineEdit_sample: BK1
    plainTextEdit_comments: Film
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 375
    spinBox_wavelength_start: 310
    spinBox_wavelength_step: 5
    spinBox_wavelength_stop: 370
  widget_powermeter_excitation_emission:
    spinBox_wavelength_alignment: 221
  widget_shuttercontrol_excitation_emission:
    checkBox: true
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 20
    spinBox_integration_time_alignment: 100
    spinBox_integration_time_experiment: 100
  widget_xystage_excitation_emission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 40.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 4
    spinBox_x_off_left: 10
    spinBox_x_off_right: 14
    spinBox_y_num: 1
    spinBox_y_off_bottom: 10
    spinBox_y_off_top: 10
lineEdit_beamsplitter_calibration_file: C:/Users/bauke/OneDrive/Bureaublad/BeamSplitter_Calibrations/BS20WR_210_1_399_nm_2110071001.csv
transmission:
  widget_file_transmission:
    comboBox_substrate: 44X44 mm (Quartz)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_filter: None
    lineEdit_sample: BK3
    plainTextEdit_comments: Testmeasurement transmission for reals
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 200
    spinBox_integration_time_experiment: 2000
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 40.0
    doubleSpinBox_y: 30.0
    spinBox_x_num: 7
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 6
    spinBox_y_off_bottom: 19
    spinBox_y_off_top: 5
