decay:
  widget_digitizer_decay:
    comboBox_samples_alignment: '4000'
    comboBox_samples_experiment: '4000'
    listWidget_channels_alignment: []
    listWidget_channels_experiment:
    - 0
    - 1
    - 2
    - 3
    spinBox_number_pulses_experiment: 50
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
  widget_file_decay:
    checkBox_append_file: true
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_append_file: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY/Decaytest.hdf5
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: Decaytest
    plainTextEdit_comments: No PMT or sample, just testing
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 220
    spinBox_wavelength_start: 220
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 220
  widget_shuttercontrol_decay:
    checkBox: true
  widget_xystage_decay:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 10.0
    doubleSpinBox_y: 10.0
    spinBox_x_num: 4
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 3
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
excitation_emission:
  widget_file_excitation_emission:
    checkBox_append_file: false
    comboBox_substrate: 0
    lineEdit_append_file: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY/Testtesttrans.hdf5
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: Realtest_vis
    plainTextEdit_comments: Harde dingen jeweet
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: 0
    spinBox_wavelength_alignment: 375
    spinBox_wavelength_start: 240
    spinBox_wavelength_step: 25
    spinBox_wavelength_stop: 375
  widget_powermeter_excitation_emission:
    spinBox_integration_time_alignment: 1
    spinBox_integration_time_experiment: 50
    spinBox_wavelength_alignment: 200
  widget_shuttercontrol_excitation_emission:
    checkBox: true
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 10
    spinBox_averageing_experiment: 10
    spinBox_integration_time_alignment: 300
    spinBox_integration_time_experiment: 300
  widget_xystage_excitation_emission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 20.0
    doubleSpinBox_y: 109.0
    spinBox_x_num: 3
    spinBox_x_off_left: 20
    spinBox_x_off_right: 20
    spinBox_y_num: 3
    spinBox_y_off_bottom: 20
    spinBox_y_off_top: 20
transmission:
  widget_file_transmission:
    checkBox_append_file: false
    comboBox_substrate: 1
    lineEdit_append_file: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY/Realtest_vis.hdf5
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: 'Newshit '
    plainTextEdit_comments: Transmission test for funzors
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 2
    spinBox_integration_time_alignment: 100
    spinBox_integration_time_experiment: 200
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 0.0
    doubleSpinBox_y: 0.0
    spinBox_x_num: 3
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 3
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
