# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digitizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(351, 497)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_experiment = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_experiment.sizePolicy().hasHeightForWidth())
        self.page_experiment.setSizePolicy(sizePolicy)
        self.page_experiment.setObjectName("page_experiment")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_experiment)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.listWidget_channels_experiment = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_channels_experiment.setMaximumSize(QtCore.QSize(16777215, 35))
        self.listWidget_channels_experiment.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_channels_experiment.setObjectName("listWidget_channels_experiment")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_experiment.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_experiment.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget_channels_experiment)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox_samples_experiment = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_samples_experiment.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_samples_experiment.setObjectName("comboBox_samples_experiment")
        self.comboBox_samples_experiment.addItem("")
        self.comboBox_samples_experiment.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_samples_experiment)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_post_trigger_size_experiment = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_post_trigger_size_experiment.setMinimum(1)
        self.spinBox_post_trigger_size_experiment.setMaximum(100)
        self.spinBox_post_trigger_size_experiment.setProperty("value", 90)
        self.spinBox_post_trigger_size_experiment.setObjectName("spinBox_post_trigger_size_experiment")
        self.horizontalLayout_2.addWidget(self.spinBox_post_trigger_size_experiment)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spinBox_number_pulses_experiment = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_number_pulses_experiment.setMinimum(1)
        self.spinBox_number_pulses_experiment.setMaximum(1000)
        self.spinBox_number_pulses_experiment.setObjectName("spinBox_number_pulses_experiment")
        self.horizontalLayout_10.addWidget(self.spinBox_number_pulses_experiment)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_experiment)
        self.page_alignment = QtWidgets.QWidget()
        self.page_alignment.setObjectName("page_alignment")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_alignment)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_samples_alignment = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_samples_alignment.sizePolicy().hasHeightForWidth())
        self.comboBox_samples_alignment.setSizePolicy(sizePolicy)
        self.comboBox_samples_alignment.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_samples_alignment.setMaximumSize(QtCore.QSize(16777215, 23))
        self.comboBox_samples_alignment.setObjectName("comboBox_samples_alignment")
        self.comboBox_samples_alignment.addItem("")
        self.comboBox_samples_alignment.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_samples_alignment)
        self.pushButton_samples_alignment = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_samples_alignment.sizePolicy().hasHeightForWidth())
        self.pushButton_samples_alignment.setSizePolicy(sizePolicy)
        self.pushButton_samples_alignment.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_samples_alignment.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_samples_alignment.setObjectName("pushButton_samples_alignment")
        self.horizontalLayout_6.addWidget(self.pushButton_samples_alignment)
        self.label_samples_indicator = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_samples_indicator.sizePolicy().hasHeightForWidth())
        self.label_samples_indicator.setSizePolicy(sizePolicy)
        self.label_samples_indicator.setMinimumSize(QtCore.QSize(60, 0))
        self.label_samples_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samples_indicator.setObjectName("label_samples_indicator")
        self.horizontalLayout_6.addWidget(self.label_samples_indicator)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.listWidget_channels_alignment = QtWidgets.QListWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_channels_alignment.sizePolicy().hasHeightForWidth())
        self.listWidget_channels_alignment.setSizePolicy(sizePolicy)
        self.listWidget_channels_alignment.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_channels_alignment.setMaximumSize(QtCore.QSize(1677215, 35))
        self.listWidget_channels_alignment.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_channels_alignment.setObjectName("listWidget_channels_alignment")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_alignment.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_alignment.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_alignment.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_channels_alignment.addItem(item)
        self.horizontalLayout_7.addWidget(self.listWidget_channels_alignment)
        self.pushButton_channel_alignment = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_channel_alignment.sizePolicy().hasHeightForWidth())
        self.pushButton_channel_alignment.setSizePolicy(sizePolicy)
        self.pushButton_channel_alignment.setMinimumSize(QtCore.QSize(0, 37))
        self.pushButton_channel_alignment.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_channel_alignment.setObjectName("pushButton_channel_alignment")
        self.horizontalLayout_7.addWidget(self.pushButton_channel_alignment)
        self.label_channel_indicator = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_channel_indicator.sizePolicy().hasHeightForWidth())
        self.label_channel_indicator.setSizePolicy(sizePolicy)
        self.label_channel_indicator.setMinimumSize(QtCore.QSize(60, 0))
        self.label_channel_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_indicator.setObjectName("label_channel_indicator")
        self.horizontalLayout_7.addWidget(self.label_channel_indicator)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBox_post_trigger_size_alignment = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_post_trigger_size_alignment.sizePolicy().hasHeightForWidth())
        self.spinBox_post_trigger_size_alignment.setSizePolicy(sizePolicy)
        self.spinBox_post_trigger_size_alignment.setMinimum(1)
        self.spinBox_post_trigger_size_alignment.setMaximum(100)
        self.spinBox_post_trigger_size_alignment.setProperty("value", 90)
        self.spinBox_post_trigger_size_alignment.setObjectName("spinBox_post_trigger_size_alignment")
        self.horizontalLayout_4.addWidget(self.spinBox_post_trigger_size_alignment)
        self.label_Post_trigger_size_indicator = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Post_trigger_size_indicator.sizePolicy().hasHeightForWidth())
        self.label_Post_trigger_size_indicator.setSizePolicy(sizePolicy)
        self.label_Post_trigger_size_indicator.setMinimumSize(QtCore.QSize(60, 0))
        self.label_Post_trigger_size_indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Post_trigger_size_indicator.setObjectName("label_Post_trigger_size_indicator")
        self.horizontalLayout_4.addWidget(self.label_Post_trigger_size_indicator)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_alignment)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Digitizer"))
        self.label_3.setText(_translate("Form", "Channel(s)"))
        __sortingEnabled = self.listWidget_channels_experiment.isSortingEnabled()
        self.listWidget_channels_experiment.setSortingEnabled(False)
        item = self.listWidget_channels_experiment.item(0)
        item.setText(_translate("Form", "0"))
        item = self.listWidget_channels_experiment.item(1)
        item.setText(_translate("Form", "1"))
        self.listWidget_channels_experiment.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Form", "Samples per Pulse"))
        self.comboBox_samples_experiment.setItemText(0, _translate("Form", "4000"))
        self.comboBox_samples_experiment.setItemText(1, _translate("Form", "8000"))
        self.label_2.setText(_translate("Form", "Post Trigger Size (1-100)"))
        self.label_10.setText(_translate("Form", "Number of Pulses"))
        self.groupBox_2.setTitle(_translate("Form", "Digitizer "))
        self.label_5.setText(_translate("Form", "Samples per Pulse"))
        self.comboBox_samples_alignment.setItemText(0, _translate("Form", "4000"))
        self.comboBox_samples_alignment.setItemText(1, _translate("Form", "8000"))
        self.pushButton_samples_alignment.setText(_translate("Form", "Set"))
        self.label_samples_indicator.setText(_translate("Form", "16000"))
        self.label_4.setText(_translate("Form", "Channel (s)"))
        __sortingEnabled = self.listWidget_channels_alignment.isSortingEnabled()
        self.listWidget_channels_alignment.setSortingEnabled(False)
        item = self.listWidget_channels_alignment.item(0)
        item.setText(_translate("Form", "0"))
        item = self.listWidget_channels_alignment.item(1)
        item.setText(_translate("Form", "1"))
        item = self.listWidget_channels_alignment.item(2)
        item.setText(_translate("Form", "2"))
        item = self.listWidget_channels_alignment.item(3)
        item.setText(_translate("Form", "3"))
        self.listWidget_channels_alignment.setSortingEnabled(__sortingEnabled)
        self.pushButton_channel_alignment.setText(_translate("Form", "Set"))
        self.label_channel_indicator.setText(_translate("Form", "1, 2, 3, 4"))
        self.label_7.setText(_translate("Form", "Post Trigger Size (1-100)"))
        self.label_Post_trigger_size_indicator.setText(_translate("Form", "90"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

