# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digitizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(532, 596)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_experiment = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_experiment.sizePolicy().hasHeightForWidth())
        self.page_experiment.setSizePolicy(sizePolicy)
        self.page_experiment.setObjectName("page_experiment")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_experiment)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(120, 0))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.comboBox_measurement_mode_experiment = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_measurement_mode_experiment.setObjectName("comboBox_measurement_mode_experiment")
        self.comboBox_measurement_mode_experiment.addItem("")
        self.comboBox_measurement_mode_experiment.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_measurement_mode_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_data_channel_experiment = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_data_channel_experiment.setObjectName("comboBox_data_channel_experiment")
        self.comboBox_data_channel_experiment.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_data_channel_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox_time_range_experiment = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_time_range_experiment.setObjectName("comboBox_time_range_experiment")
        self.comboBox_time_range_experiment.addItem("")
        self.comboBox_time_range_experiment.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_time_range_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_post_trigger_size_experiment = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_post_trigger_size_experiment.setMinimum(1)
        self.spinBox_post_trigger_size_experiment.setMaximum(100)
        self.spinBox_post_trigger_size_experiment.setProperty("value", 90)
        self.spinBox_post_trigger_size_experiment.setObjectName("spinBox_post_trigger_size_experiment")
        self.horizontalLayout_2.addWidget(self.spinBox_post_trigger_size_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(120, 0))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.spinBox_dc_offset_experiment = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_dc_offset_experiment.setObjectName("spinBox_dc_offset_experiment")
        self.horizontalLayout_19.addWidget(self.spinBox_dc_offset_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_19, 4, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(120, 0))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.comboBox_jitter_channel_experiment = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_jitter_channel_experiment.setObjectName("comboBox_jitter_channel_experiment")
        self.horizontalLayout_20.addWidget(self.comboBox_jitter_channel_experiment)
        self.checkBox_jitter_correction_experiment = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_jitter_correction_experiment.setObjectName("checkBox_jitter_correction_experiment")
        self.horizontalLayout_20.addWidget(self.checkBox_jitter_correction_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_20, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.spinBox_number_pulses_experiment = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_number_pulses_experiment.setMinimum(1)
        self.spinBox_number_pulses_experiment.setMaximum(1000)
        self.spinBox_number_pulses_experiment.setObjectName("spinBox_number_pulses_experiment")
        self.horizontalLayout_10.addWidget(self.spinBox_number_pulses_experiment)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 6, 0, 1, 1)
        self.groupBox_single_photon_experiment = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_single_photon_experiment.setObjectName("groupBox_single_photon_experiment")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_single_photon_experiment)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.groupBox_single_photon_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(120, 0))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.comboBox_single_photon_compression_experiment = QtWidgets.QComboBox(self.groupBox_single_photon_experiment)
        self.comboBox_single_photon_compression_experiment.setObjectName("comboBox_single_photon_compression_experiment")
        self.horizontalLayout_21.addWidget(self.comboBox_single_photon_compression_experiment)
        self.gridLayout_3.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.groupBox_single_photon_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(120, 0))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.spinBox_single_photon_treshold_experiment = QtWidgets.QSpinBox(self.groupBox_single_photon_experiment)
        self.spinBox_single_photon_treshold_experiment.setObjectName("spinBox_single_photon_treshold_experiment")
        self.horizontalLayout_22.addWidget(self.spinBox_single_photon_treshold_experiment)
        self.gridLayout_3.addLayout(self.horizontalLayout_22, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_single_photon_experiment, 7, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_experiment)
        self.page_alignment = QtWidgets.QWidget()
        self.page_alignment.setObjectName("page_alignment")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_alignment)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.comboBox_measurement_mode_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_measurement_mode_alignment.setObjectName("comboBox_measurement_mode_alignment")
        self.comboBox_measurement_mode_alignment.addItem("")
        self.comboBox_measurement_mode_alignment.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_measurement_mode_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.comboBox_data_channel_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_data_channel_alignment.setObjectName("comboBox_data_channel_alignment")
        self.comboBox_data_channel_alignment.addItem("")
        self.comboBox_data_channel_alignment.addItem("")
        self.comboBox_data_channel_alignment.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_data_channel_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox_time_range_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_time_range_alignment.setObjectName("comboBox_time_range_alignment")
        self.comboBox_time_range_alignment.addItem("")
        self.comboBox_time_range_alignment.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_time_range_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.spinBox_dc_offset_alignment = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_dc_offset_alignment.setObjectName("spinBox_dc_offset_alignment")
        self.horizontalLayout_9.addWidget(self.spinBox_dc_offset_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.spinBox_post_trigger_size_alignment = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_post_trigger_size_alignment.sizePolicy().hasHeightForWidth())
        self.spinBox_post_trigger_size_alignment.setSizePolicy(sizePolicy)
        self.spinBox_post_trigger_size_alignment.setMinimum(1)
        self.spinBox_post_trigger_size_alignment.setMaximum(100)
        self.spinBox_post_trigger_size_alignment.setProperty("value", 90)
        self.spinBox_post_trigger_size_alignment.setObjectName("spinBox_post_trigger_size_alignment")
        self.horizontalLayout_4.addWidget(self.spinBox_post_trigger_size_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_jitter_channel_alignment = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_jitter_channel_alignment.setObjectName("comboBox_jitter_channel_alignment")
        self.horizontalLayout_8.addWidget(self.comboBox_jitter_channel_alignment)
        self.checkBox_jitter_correction_alignment = QtWidgets.QCheckBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_jitter_correction_alignment.sizePolicy().hasHeightForWidth())
        self.checkBox_jitter_correction_alignment.setSizePolicy(sizePolicy)
        self.checkBox_jitter_correction_alignment.setObjectName("checkBox_jitter_correction_alignment")
        self.horizontalLayout_8.addWidget(self.checkBox_jitter_correction_alignment)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 5, 0, 1, 1)
        self.groupBox_single_photon_alignment = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_single_photon_alignment.sizePolicy().hasHeightForWidth())
        self.groupBox_single_photon_alignment.setSizePolicy(sizePolicy)
        self.groupBox_single_photon_alignment.setObjectName("groupBox_single_photon_alignment")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_single_photon_alignment)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_single_photon_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(111, 0))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.comboBox_single_photon_compression_alignment = QtWidgets.QComboBox(self.groupBox_single_photon_alignment)
        self.comboBox_single_photon_compression_alignment.setObjectName("comboBox_single_photon_compression_alignment")
        self.comboBox_single_photon_compression_alignment.addItem("")
        self.comboBox_single_photon_compression_alignment.addItem("")
        self.comboBox_single_photon_compression_alignment.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_single_photon_compression_alignment)
        self.pushButton_single_photon_clear_alignment = QtWidgets.QPushButton(self.groupBox_single_photon_alignment)
        self.pushButton_single_photon_clear_alignment.setObjectName("pushButton_single_photon_clear_alignment")
        self.horizontalLayout_11.addWidget(self.pushButton_single_photon_clear_alignment)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.groupBox_single_photon_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(111, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.spinBox_single_photon_treshold_alignment = QtWidgets.QSpinBox(self.groupBox_single_photon_alignment)
        self.spinBox_single_photon_treshold_alignment.setObjectName("spinBox_single_photon_treshold_alignment")
        self.horizontalLayout_23.addWidget(self.spinBox_single_photon_treshold_alignment)
        self.gridLayout_5.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_single_photon_alignment, 6, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_alignment)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Digitizer"))
        self.label_18.setText(_translate("Form", "Measurement Mode"))
        self.comboBox_measurement_mode_experiment.setItemText(0, _translate("Form", "multiple pulses averaged"))
        self.comboBox_measurement_mode_experiment.setItemText(1, _translate("Form", "single photon counting"))
        self.label_3.setText(_translate("Form", "Data Channel"))
        self.comboBox_data_channel_experiment.setItemText(0, _translate("Form", "0"))
        self.label.setText(_translate("Form", "Time Range"))
        self.comboBox_time_range_experiment.setItemText(0, _translate("Form", "10 ns "))
        self.comboBox_time_range_experiment.setItemText(1, _translate("Form", "20 ns "))
        self.label_2.setText(_translate("Form", "Post Trigger Size (1-100)"))
        self.label_19.setText(_translate("Form", "DC Offset"))
        self.label_20.setText(_translate("Form", "Jitter Channel"))
        self.checkBox_jitter_correction_experiment.setText(_translate("Form", "Enable Jitter Correction"))
        self.label_10.setText(_translate("Form", "Number of Pulses"))
        self.groupBox_single_photon_experiment.setTitle(_translate("Form", "Single Photon Counting"))
        self.label_21.setText(_translate("Form", "Compression "))
        self.label_22.setText(_translate("Form", "Treshold"))
        self.groupBox_2.setTitle(_translate("Form", "Digitizer "))
        self.label_6.setText(_translate("Form", "Measurement Mode"))
        self.comboBox_measurement_mode_alignment.setItemText(0, _translate("Form", "single pulse"))
        self.comboBox_measurement_mode_alignment.setItemText(1, _translate("Form", "single photon counting"))
        self.label_4.setText(_translate("Form", "Data Channel"))
        self.comboBox_data_channel_alignment.setItemText(0, _translate("Form", "0"))
        self.comboBox_data_channel_alignment.setItemText(1, _translate("Form", "1"))
        self.comboBox_data_channel_alignment.setItemText(2, _translate("Form", "2"))
        self.label_5.setText(_translate("Form", "Timerange"))
        self.comboBox_time_range_alignment.setItemText(0, _translate("Form", "40 μs"))
        self.comboBox_time_range_alignment.setItemText(1, _translate("Form", "80 μs"))
        self.label_8.setText(_translate("Form", "DC Offset (0-100)"))
        self.label_7.setText(_translate("Form", "Post Trigger Size (1-100)"))
        self.label_9.setText(_translate("Form", "Jitter Channel"))
        self.checkBox_jitter_correction_alignment.setText(_translate("Form", "Enable Jitter Correction"))
        self.groupBox_single_photon_alignment.setTitle(_translate("Form", "Single Photon Counting"))
        self.label_12.setText(_translate("Form", "Compression"))
        self.comboBox_single_photon_compression_alignment.setItemText(0, _translate("Form", "None"))
        self.comboBox_single_photon_compression_alignment.setItemText(1, _translate("Form", "20 ns"))
        self.comboBox_single_photon_compression_alignment.setItemText(2, _translate("Form", "50 ns"))
        self.pushButton_single_photon_clear_alignment.setText(_translate("Form", "Clear"))
        self.label_23.setText(_translate("Form", "Treshold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

