# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laser.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(166, 104)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_experiment = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_experiment.sizePolicy().hasHeightForWidth())
        self.page_experiment.setSizePolicy(sizePolicy)
        self.page_experiment.setObjectName("page_experiment")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_experiment)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_laser = QtWidgets.QGroupBox(self.page_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_laser.sizePolicy().hasHeightForWidth())
        self.groupBox_laser.setSizePolicy(sizePolicy)
        self.groupBox_laser.setObjectName("groupBox_laser")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_laser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_wavelength_start = QtWidgets.QLabel(self.groupBox_laser)
        self.label_wavelength_start.setObjectName("label_wavelength_start")
        self.horizontalLayout_3.addWidget(self.label_wavelength_start)
        self.doubleSpinBox_wavelength_start = QtWidgets.QDoubleSpinBox(self.groupBox_laser)
        self.doubleSpinBox_wavelength_start.setMinimumSize(QtCore.QSize(20, 0))
        self.doubleSpinBox_wavelength_start.setObjectName("doubleSpinBox_wavelength_start")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_wavelength_start)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_wavelength_stop = QtWidgets.QLabel(self.groupBox_laser)
        self.label_wavelength_stop.setObjectName("label_wavelength_stop")
        self.horizontalLayout_2.addWidget(self.label_wavelength_stop)
        self.doubleSpinBox_wavelength_stop = QtWidgets.QDoubleSpinBox(self.groupBox_laser)
        self.doubleSpinBox_wavelength_stop.setMinimumSize(QtCore.QSize(20, 0))
        self.doubleSpinBox_wavelength_stop.setObjectName("doubleSpinBox_wavelength_stop")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_wavelength_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_wavelength_step = QtWidgets.QLabel(self.groupBox_laser)
        self.label_wavelength_step.setObjectName("label_wavelength_step")
        self.horizontalLayout.addWidget(self.label_wavelength_step)
        self.doubleSpinBox_wavelength_step = QtWidgets.QDoubleSpinBox(self.groupBox_laser)
        self.doubleSpinBox_wavelength_step.setMinimumSize(QtCore.QSize(20, 0))
        self.doubleSpinBox_wavelength_step.setObjectName("doubleSpinBox_wavelength_step")
        self.horizontalLayout.addWidget(self.doubleSpinBox_wavelength_step)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_laser, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_experiment)
        self.page_alignment = QtWidgets.QWidget()
        self.page_alignment.setObjectName("page_alignment")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_alignment)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.page_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_wavelength = QtWidgets.QLabel(self.groupBox)
        self.label_wavelength.setObjectName("label_wavelength")
        self.horizontalLayout_4.addWidget(self.label_wavelength)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_alignment)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_laser.setTitle(_translate("Form", "Laser Wavelength"))
        self.label_wavelength_start.setText(_translate("Form", "start (nm)"))
        self.label_wavelength_stop.setText(_translate("Form", "stop (nm) "))
        self.label_wavelength_step.setText(_translate("Form", "step (nm) "))
        self.groupBox.setTitle(_translate("Form", "Laser (nm) "))
        self.label_wavelength.setText(_translate("Form", "Wavelength (nm)"))
        self.pushButton.setText(_translate("Form", "Off"))
        self.pushButton_3.setText(_translate("Form", "Adjust"))
        self.pushButton_4.setText(_translate("Form", "Max"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

