# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(876, 649)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_intro = QtWidgets.QWidget()
        self.page_intro.setObjectName("page_intro")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_intro)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_intro = QtWidgets.QGridLayout()
        self.gridLayout_intro.setObjectName("gridLayout_intro")
        self.label_introText = QtWidgets.QLabel(self.page_intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_introText.sizePolicy().hasHeightForWidth())
        self.label_introText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_introText.setFont(font)
        self.label_introText.setAlignment(QtCore.Qt.AlignCenter)
        self.label_introText.setObjectName("label_introText")
        self.gridLayout_intro.addWidget(self.label_introText, 0, 0, 1, 1)
        self.pushButton_transmission = QtWidgets.QPushButton(self.page_intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_transmission.sizePolicy().hasHeightForWidth())
        self.pushButton_transmission.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_transmission.setFont(font)
        self.pushButton_transmission.setObjectName("pushButton_transmission")
        self.gridLayout_intro.addWidget(self.pushButton_transmission, 1, 0, 1, 1)
        self.pushButton_excitationEmission = QtWidgets.QPushButton(self.page_intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_excitationEmission.sizePolicy().hasHeightForWidth())
        self.pushButton_excitationEmission.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_excitationEmission.setFont(font)
        self.pushButton_excitationEmission.setObjectName("pushButton_excitationEmission")
        self.gridLayout_intro.addWidget(self.pushButton_excitationEmission, 2, 0, 1, 1)
        self.pushButton_decay = QtWidgets.QPushButton(self.page_intro)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_decay.sizePolicy().hasHeightForWidth())
        self.pushButton_decay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_decay.setFont(font)
        self.pushButton_decay.setObjectName("pushButton_decay")
        self.gridLayout_intro.addWidget(self.pushButton_decay, 3, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_intro, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_intro)
        self.page_experiment = QtWidgets.QWidget()
        self.page_experiment.setObjectName("page_experiment")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_experiment)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget_experiment = QtWidgets.QStackedWidget(self.page_experiment)
        self.stackedWidget_experiment.setObjectName("stackedWidget_experiment")
        self.page_transmission = QtWidgets.QWidget()
        self.page_transmission.setObjectName("page_transmission")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_transmission)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_spectrometer_transmission = SpectrometerWidget(self.page_transmission)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_spectrometer_transmission.sizePolicy().hasHeightForWidth())
        self.widget_spectrometer_transmission.setSizePolicy(sizePolicy)
        self.widget_spectrometer_transmission.setObjectName("widget_spectrometer_transmission")
        self.gridLayout_6.addWidget(self.widget_spectrometer_transmission, 0, 0, 1, 1)
        self.verticalLayout_transmission = QtWidgets.QVBoxLayout()
        self.verticalLayout_transmission.setObjectName("verticalLayout_transmission")
        self.widget_file_transmission = FileWidget(self.page_transmission)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_file_transmission.sizePolicy().hasHeightForWidth())
        self.widget_file_transmission.setSizePolicy(sizePolicy)
        self.widget_file_transmission.setObjectName("widget_file_transmission")
        self.verticalLayout_transmission.addWidget(self.widget_file_transmission)
        self.widget_motor_transmission = MotorWidget(self.page_transmission)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_motor_transmission.sizePolicy().hasHeightForWidth())
        self.widget_motor_transmission.setSizePolicy(sizePolicy)
        self.widget_motor_transmission.setObjectName("widget_motor_transmission")
        self.verticalLayout_transmission.addWidget(self.widget_motor_transmission)
        self.gridLayout_6.addLayout(self.verticalLayout_transmission, 0, 1, 1, 1)
        self.stackedWidget_experiment.addWidget(self.page_transmission)
        self.page_excitation_emission = QtWidgets.QWidget()
        self.page_excitation_emission.setObjectName("page_excitation_emission")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_excitation_emission)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_excitation_Emission_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_excitation_Emission_left.setObjectName("verticalLayout_excitation_Emission_left")
        self.widget_spectrometer_excitationEmission = SpectrometerWidget(self.page_excitation_emission)
        self.widget_spectrometer_excitationEmission.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_spectrometer_excitationEmission.setObjectName("widget_spectrometer_excitationEmission")
        self.verticalLayout_excitation_Emission_left.addWidget(self.widget_spectrometer_excitationEmission)
        self.widget_powermeter_excitationEmission = PowerMeterWidget(self.page_excitation_emission)
        self.widget_powermeter_excitationEmission.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_powermeter_excitationEmission.setObjectName("widget_powermeter_excitationEmission")
        self.verticalLayout_excitation_Emission_left.addWidget(self.widget_powermeter_excitationEmission)
        self.gridLayout_5.addLayout(self.verticalLayout_excitation_Emission_left, 0, 0, 1, 1)
        self.verticalLayout_excitationEmission_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_excitationEmission_right.setObjectName("verticalLayout_excitationEmission_right")
        self.widget_file_excitationEmission = FileWidget(self.page_excitation_emission)
        self.widget_file_excitationEmission.setMinimumSize(QtCore.QSize(80, 100))
        self.widget_file_excitationEmission.setObjectName("widget_file_excitationEmission")
        self.verticalLayout_excitationEmission_right.addWidget(self.widget_file_excitationEmission)
        self.widget_motor_excitationEmission = MotorWidget(self.page_excitation_emission)
        self.widget_motor_excitationEmission.setMinimumSize(QtCore.QSize(80, 100))
        self.widget_motor_excitationEmission.setObjectName("widget_motor_excitationEmission")
        self.verticalLayout_excitationEmission_right.addWidget(self.widget_motor_excitationEmission)
        self.widget_laser_excitationEmission = LaserWidget(self.page_excitation_emission)
        self.widget_laser_excitationEmission.setObjectName("widget_laser_excitationEmission")
        self.verticalLayout_excitationEmission_right.addWidget(self.widget_laser_excitationEmission)
        self.gridLayout_5.addLayout(self.verticalLayout_excitationEmission_right, 0, 1, 1, 1)
        self.stackedWidget_experiment.addWidget(self.page_excitation_emission)
        self.page_decay = QtWidgets.QWidget()
        self.page_decay.setObjectName("page_decay")
        self.gridLayout = QtWidgets.QGridLayout(self.page_decay)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_spectrometer_decay = SpectrometerWidget(self.page_decay)
        self.widget_spectrometer_decay.setMinimumSize(QtCore.QSize(100, 100))
        self.widget_spectrometer_decay.setObjectName("widget_spectrometer_decay")
        self.verticalLayout.addWidget(self.widget_spectrometer_decay)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_file_decay = FileWidget(self.page_decay)
        self.widget_file_decay.setMinimumSize(QtCore.QSize(80, 80))
        self.widget_file_decay.setObjectName("widget_file_decay")
        self.verticalLayout_2.addWidget(self.widget_file_decay)
        self.widget_motor_decay = MotorWidget(self.page_decay)
        self.widget_motor_decay.setMinimumSize(QtCore.QSize(80, 80))
        self.widget_motor_decay.setObjectName("widget_motor_decay")
        self.verticalLayout_2.addWidget(self.widget_motor_decay)
        self.widget_laser_decay = LaserWidget(self.page_decay)
        self.widget_laser_decay.setMinimumSize(QtCore.QSize(80, 80))
        self.widget_laser_decay.setObjectName("widget_laser_decay")
        self.verticalLayout_2.addWidget(self.widget_laser_decay)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.stackedWidget_experiment.addWidget(self.page_decay)
        self.gridLayout_2.addWidget(self.stackedWidget_experiment, 0, 0, 1, 1)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.pushButton_Return = QtWidgets.QPushButton(self.page_experiment)
        self.pushButton_Return.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Return.setFont(font)
        self.pushButton_Return.setObjectName("pushButton_Return")
        self.horizontalLayout_buttons.addWidget(self.pushButton_Return)
        self.pushButton_StartExperiment = QtWidgets.QPushButton(self.page_experiment)
        self.pushButton_StartExperiment.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_StartExperiment.setFont(font)
        self.pushButton_StartExperiment.setObjectName("pushButton_StartExperiment")
        self.horizontalLayout_buttons.addWidget(self.pushButton_StartExperiment)
        self.gridLayout_2.addLayout(self.horizontalLayout_buttons, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_experiment)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_experiment.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_introText.setText(_translate("MainWindow", "Choose an experiment type:"))
        self.pushButton_transmission.setText(_translate("MainWindow", "Transmission"))
        self.pushButton_excitationEmission.setText(_translate("MainWindow", "Excitation Emission"))
        self.pushButton_decay.setText(_translate("MainWindow", "Decay"))
        self.pushButton_Return.setText(_translate("MainWindow", "Return"))
        self.pushButton_StartExperiment.setText(_translate("MainWindow", "Start Experiment"))

from gui_action.widget_file import FileWidget
from gui_action.widget_laser import LaserWidget
from gui_action.widget_motor import MotorWidget
from gui_action.widget_powermeter import PowerMeterWidget
from gui_action.widget_spectrometer import SpectrometerWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

