# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(464, 288)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_xstart = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xstart.sizePolicy().hasHeightForWidth())
        self.label_xstart.setSizePolicy(sizePolicy)
        self.label_xstart.setMinimumSize(QtCore.QSize(60, 0))
        self.label_xstart.setObjectName("label_xstart")
        self.horizontalLayout.addWidget(self.label_xstart)
        self.doubleSpinBox_xstart = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xstart.setObjectName("doubleSpinBox_xstart")
        self.horizontalLayout.addWidget(self.doubleSpinBox_xstart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_xstop = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xstop.sizePolicy().hasHeightForWidth())
        self.label_xstop.setSizePolicy(sizePolicy)
        self.label_xstop.setMinimumSize(QtCore.QSize(60, 0))
        self.label_xstop.setObjectName("label_xstop")
        self.horizontalLayout_3.addWidget(self.label_xstop)
        self.doubleSpinBox_xstop = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xstop.setObjectName("doubleSpinBox_xstop")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_xstop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_xnum = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xnum.sizePolicy().hasHeightForWidth())
        self.label_xnum.setSizePolicy(sizePolicy)
        self.label_xnum.setMinimumSize(QtCore.QSize(60, 0))
        self.label_xnum.setObjectName("label_xnum")
        self.horizontalLayout_4.addWidget(self.label_xnum)
        self.doubleSpinBox_xnum = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xnum.setObjectName("doubleSpinBox_xnum")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_xnum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_ystart = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ystart.sizePolicy().hasHeightForWidth())
        self.label_ystart.setSizePolicy(sizePolicy)
        self.label_ystart.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ystart.setObjectName("label_ystart")
        self.horizontalLayout_5.addWidget(self.label_ystart)
        self.doubleSpinBox_ystart = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ystart.setObjectName("doubleSpinBox_ystart")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_ystart)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ystop = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ystop.sizePolicy().hasHeightForWidth())
        self.label_ystop.setSizePolicy(sizePolicy)
        self.label_ystop.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ystop.setObjectName("label_ystop")
        self.horizontalLayout_6.addWidget(self.label_ystop)
        self.doubleSpinBox_ystop = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ystop.setObjectName("doubleSpinBox_ystop")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_ystop)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_ynum = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ynum.sizePolicy().hasHeightForWidth())
        self.label_ynum.setSizePolicy(sizePolicy)
        self.label_ynum.setMinimumSize(QtCore.QSize(60, 0))
        self.label_ynum.setObjectName("label_ynum")
        self.horizontalLayout_7.addWidget(self.label_ynum)
        self.doubleSpinBox_ynum = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ynum.setObjectName("doubleSpinBox_ynum")
        self.horizontalLayout_7.addWidget(self.doubleSpinBox_ynum)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_fromhere = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fromhere.sizePolicy().hasHeightForWidth())
        self.pushButton_fromhere.setSizePolicy(sizePolicy)
        self.pushButton_fromhere.setObjectName("pushButton_fromhere")
        self.horizontalLayout_8.addWidget(self.pushButton_fromhere)
        self.pushButton__tohere = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton__tohere.sizePolicy().hasHeightForWidth())
        self.pushButton__tohere.setSizePolicy(sizePolicy)
        self.pushButton__tohere.setObjectName("pushButton__tohere")
        self.horizontalLayout_8.addWidget(self.pushButton__tohere)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "XY Stages"))
        self.label_xstart.setText(_translate("Form", "x start (mm)"))
        self.label_xstop.setText(_translate("Form", "x stop (mm)"))
        self.label_xnum.setText(_translate("Form", "x num (#)"))
        self.label_ystart.setText(_translate("Form", "y start (mm)"))
        self.label_ystop.setText(_translate("Form", "y stop (mm)"))
        self.label_ynum.setText(_translate("Form", "y num (mm)"))
        self.pushButton_fromhere.setText(_translate("Form", "From here"))
        self.pushButton__tohere.setText(_translate("Form", "To here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

