# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(151, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_experiment = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_experiment.sizePolicy().hasHeightForWidth())
        self.page_experiment.setSizePolicy(sizePolicy)
        self.page_experiment.setObjectName("page_experiment")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_experiment)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_experiment = QtWidgets.QGroupBox(self.page_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_experiment.sizePolicy().hasHeightForWidth())
        self.groupBox_experiment.setSizePolicy(sizePolicy)
        self.groupBox_experiment.setMinimumSize(QtCore.QSize(0, 204))
        self.groupBox_experiment.setObjectName("groupBox_experiment")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_experiment)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_x_start = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_x_start.setMinimumSize(QtCore.QSize(60, 0))
        self.label_x_start.setObjectName("label_x_start")
        self.horizontalLayout.addWidget(self.label_x_start)
        self.doubleSpinBox_x_start = QtWidgets.QDoubleSpinBox(self.groupBox_experiment)
        self.doubleSpinBox_x_start.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_x_start.setObjectName("doubleSpinBox_x_start")
        self.horizontalLayout.addWidget(self.doubleSpinBox_x_start)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_x_stop = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_x_stop.setMinimumSize(QtCore.QSize(60, 0))
        self.label_x_stop.setObjectName("label_x_stop")
        self.horizontalLayout_3.addWidget(self.label_x_stop)
        self.doubleSpinBox_x_stop = QtWidgets.QDoubleSpinBox(self.groupBox_experiment)
        self.doubleSpinBox_x_stop.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_x_stop.setObjectName("doubleSpinBox_x_stop")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_x_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_x_num = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_x_num.setMinimumSize(QtCore.QSize(60, 0))
        self.label_x_num.setObjectName("label_x_num")
        self.horizontalLayout_4.addWidget(self.label_x_num)
        self.spinBox_x_num = QtWidgets.QSpinBox(self.groupBox_experiment)
        self.spinBox_x_num.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_x_num.setObjectName("spinBox_x_num")
        self.horizontalLayout_4.addWidget(self.spinBox_x_num)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_y_start = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_y_start.setMinimumSize(QtCore.QSize(60, 0))
        self.label_y_start.setObjectName("label_y_start")
        self.horizontalLayout_5.addWidget(self.label_y_start)
        self.doubleSpinBox_y_start = QtWidgets.QDoubleSpinBox(self.groupBox_experiment)
        self.doubleSpinBox_y_start.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_y_start.setObjectName("doubleSpinBox_y_start")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_y_start)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_y_stop = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_y_stop.setMinimumSize(QtCore.QSize(60, 0))
        self.label_y_stop.setObjectName("label_y_stop")
        self.horizontalLayout_6.addWidget(self.label_y_stop)
        self.doubleSpinBox_y_stop = QtWidgets.QDoubleSpinBox(self.groupBox_experiment)
        self.doubleSpinBox_y_stop.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBox_y_stop.setObjectName("doubleSpinBox_y_stop")
        self.horizontalLayout_6.addWidget(self.doubleSpinBox_y_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_y_num = QtWidgets.QLabel(self.groupBox_experiment)
        self.label_y_num.setMinimumSize(QtCore.QSize(60, 0))
        self.label_y_num.setObjectName("label_y_num")
        self.horizontalLayout_7.addWidget(self.label_y_num)
        self.spinBox_y_num = QtWidgets.QSpinBox(self.groupBox_experiment)
        self.spinBox_y_num.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_y_num.setObjectName("spinBox_y_num")
        self.horizontalLayout_7.addWidget(self.spinBox_y_num)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_fromhere = QtWidgets.QPushButton(self.groupBox_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_fromhere.sizePolicy().hasHeightForWidth())
        self.pushButton_fromhere.setSizePolicy(sizePolicy)
        self.pushButton_fromhere.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_fromhere.setObjectName("pushButton_fromhere")
        self.horizontalLayout_8.addWidget(self.pushButton_fromhere)
        self.pushButton_tohere = QtWidgets.QPushButton(self.groupBox_experiment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_tohere.sizePolicy().hasHeightForWidth())
        self.pushButton_tohere.setSizePolicy(sizePolicy)
        self.pushButton_tohere.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_tohere.setObjectName("pushButton_tohere")
        self.horizontalLayout_8.addWidget(self.pushButton_tohere)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_experiment, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_experiment)
        self.page_alignment = QtWidgets.QWidget()
        self.page_alignment.setObjectName("page_alignment")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_alignment)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_alignment = QtWidgets.QGroupBox(self.page_alignment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_alignment.sizePolicy().hasHeightForWidth())
        self.groupBox_alignment.setSizePolicy(sizePolicy)
        self.groupBox_alignment.setObjectName("groupBox_alignment")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_alignment)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_x = QtWidgets.QLabel(self.groupBox_alignment)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_9.addWidget(self.label_x)
        self.doubleSpinBox_x = QtWidgets.QDoubleSpinBox(self.groupBox_alignment)
        self.doubleSpinBox_x.setObjectName("doubleSpinBox_x")
        self.horizontalLayout_9.addWidget(self.doubleSpinBox_x)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_y = QtWidgets.QLabel(self.groupBox_alignment)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_2.addWidget(self.label_y)
        self.doubleSpinBox_y = QtWidgets.QDoubleSpinBox(self.groupBox_alignment)
        self.doubleSpinBox_y.setObjectName("doubleSpinBox_y")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pushButton_home_motors = QtWidgets.QPushButton(self.groupBox_alignment)
        self.pushButton_home_motors.setObjectName("pushButton_home_motors")
        self.verticalLayout_2.addWidget(self.pushButton_home_motors)
        self.gridLayout_5.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_alignment, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_alignment)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_experiment.setTitle(_translate("Form", "XY Stages"))
        self.label_x_start.setText(_translate("Form", "x start (mm)"))
        self.label_x_stop.setText(_translate("Form", "x stop (mm)"))
        self.label_x_num.setText(_translate("Form", "x num (#)"))
        self.label_y_start.setText(_translate("Form", "y start (mm)"))
        self.label_y_stop.setText(_translate("Form", "y stop (mm)"))
        self.label_y_num.setText(_translate("Form", "y num (mm)"))
        self.pushButton_fromhere.setText(_translate("Form", "from here"))
        self.pushButton_tohere.setText(_translate("Form", "to here"))
        self.groupBox_alignment.setTitle(_translate("Form", "XY Stages"))
        self.label_x.setText(_translate("Form", "x (mm)"))
        self.label_y.setText(_translate("Form", "y (mm)"))
        self.pushButton_home_motors.setText(_translate("Form", "home motors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

