# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powermeter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(286, 202)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_powermeter = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_powermeter.sizePolicy().hasHeightForWidth())
        self.groupBox_powermeter.setSizePolicy(sizePolicy)
        self.groupBox_powermeter.setObjectName("groupBox_powermeter")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_powermeter)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_integration_time = QtWidgets.QLabel(self.groupBox_powermeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_integration_time.sizePolicy().hasHeightForWidth())
        self.label_integration_time.setSizePolicy(sizePolicy)
        self.label_integration_time.setMinimumSize(QtCore.QSize(100, 0))
        self.label_integration_time.setObjectName("label_integration_time")
        self.horizontalLayout.addWidget(self.label_integration_time)
        self.spinBox_integration_time = QtWidgets.QSpinBox(self.groupBox_powermeter)
        self.spinBox_integration_time.setMinimum(1)
        self.spinBox_integration_time.setMaximum(100000)
        self.spinBox_integration_time.setObjectName("spinBox_integration_time")
        self.horizontalLayout.addWidget(self.spinBox_integration_time)
        self.label_indicator_integration_time = QtWidgets.QLabel(self.groupBox_powermeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_indicator_integration_time.sizePolicy().hasHeightForWidth())
        self.label_indicator_integration_time.setSizePolicy(sizePolicy)
        self.label_indicator_integration_time.setMinimumSize(QtCore.QSize(45, 0))
        self.label_indicator_integration_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_indicator_integration_time.setObjectName("label_indicator_integration_time")
        self.horizontalLayout.addWidget(self.label_indicator_integration_time)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_wavelength = QtWidgets.QLabel(self.groupBox_powermeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_wavelength.sizePolicy().hasHeightForWidth())
        self.label_wavelength.setSizePolicy(sizePolicy)
        self.label_wavelength.setMinimumSize(QtCore.QSize(100, 0))
        self.label_wavelength.setObjectName("label_wavelength")
        self.horizontalLayout_2.addWidget(self.label_wavelength)
        self.spinBox_wavelength = QtWidgets.QSpinBox(self.groupBox_powermeter)
        self.spinBox_wavelength.setMinimum(200)
        self.spinBox_wavelength.setMaximum(1100)
        self.spinBox_wavelength.setObjectName("spinBox_wavelength")
        self.horizontalLayout_2.addWidget(self.spinBox_wavelength)
        self.label_indicator_wavelength = QtWidgets.QLabel(self.groupBox_powermeter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_indicator_wavelength.sizePolicy().hasHeightForWidth())
        self.label_indicator_wavelength.setSizePolicy(sizePolicy)
        self.label_indicator_wavelength.setMinimumSize(QtCore.QSize(45, 0))
        self.label_indicator_wavelength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_indicator_wavelength.setObjectName("label_indicator_wavelength")
        self.horizontalLayout_2.addWidget(self.label_indicator_wavelength)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_power_title = QtWidgets.QLabel(self.groupBox_powermeter)
        self.label_power_title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_power_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_power_title.setObjectName("label_power_title")
        self.horizontalLayout_3.addWidget(self.label_power_title)
        self.label_power_value_unit = QtWidgets.QLabel(self.groupBox_powermeter)
        self.label_power_value_unit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_power_value_unit.setObjectName("label_power_value_unit")
        self.horizontalLayout_3.addWidget(self.label_power_value_unit)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.pushButton_zero = QtWidgets.QPushButton(self.groupBox_powermeter)
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.gridLayout.addWidget(self.pushButton_zero, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_powermeter, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_powermeter.setTitle(_translate("Form", "Powermeter"))
        self.label_integration_time.setText(_translate("Form", "integration time (ms)"))
        self.label_indicator_integration_time.setText(_translate("Form", "5000 ms"))
        self.label_wavelength.setText(_translate("Form", "wavelength"))
        self.label_indicator_wavelength.setText(_translate("Form", "375 nm"))
        self.label_power_title.setText(_translate("Form", "power "))
        self.label_power_value_unit.setText(_translate("Form", "300 uW"))
        self.pushButton_zero.setText(_translate("Form", "Zero Measurement"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

