decay:
  widget_digitizer_decay:
    checkBox_jitter_correction_alignment: false
    checkBox_jitter_correction_experiment: false
    comboBox_data_channel_alignment: '0'
    comboBox_data_channel_experiment: '0'
    comboBox_jitter_channel_alignment: '1'
    comboBox_jitter_channel_experiment: '1'
    comboBox_measurement_mode_alignment: single pulse
    comboBox_measurement_mode_experiment: averageing
    comboBox_single_photon_compression_alignment: none
    comboBox_time_range_alignment: "40 \u03BCs"
    comboBox_time_range_experiment: "40 \u03BCs"
    spinBox_dc_offset_alignment: 9
    spinBox_dc_offset_experiment: 10
    spinBox_number_pulses_experiment: 200
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
    spinBox_single_photon_treshold_alignment: 780
    spinBox_single_photon_treshold_experiment: 780
  widget_file_decay:
    comboBox_bandpass_filter: 680 nm - 10 nm - Thorlabs FB680-10-1 V 1-33-11
    comboBox_longpass_filter: 430 nm - Semrock FF01-430/LP-25
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/Max/211209_Decay420nm_SR2
    lineEdit_sample: SR2Test
    plainTextEdit_comments: Position BBRR
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 420
    spinBox_wavelength_start: 420
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 420
  widget_shuttercontrol_decay:
    checkBox: true
  widget_xystage_decay:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 0.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 1
    spinBox_x_off_left: 98
    spinBox_x_off_right: 0
    spinBox_y_num: 1
    spinBox_y_off_bottom: 0
    spinBox_y_off_top: 100
excitation_emission:
  widget_file_excitation_emission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/XY Test Data
    lineEdit_sample: SR8D
    plainTextEdit_comments: As deposited
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 480
    spinBox_wavelength_start: 420
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 420
  widget_powermeter_excitation_emission: {}
  widget_shuttercontrol_excitation_emission:
    checkBox: true
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 500
    spinBox_integration_time_experiment: 500
  widget_xystage_excitation_emission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 40.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 2
    spinBox_x_off_left: 10
    spinBox_x_off_right: 80
    spinBox_y_num: 1
    spinBox_y_off_bottom: 60
    spinBox_y_off_top: 25
lineEdit_beamsplitter_calibration_file: C:/Users/tud257183/Desktop/XY Test Data/BeamSplitter_Calibrations/BSC_Quartz_210_1_600_withzeroing_nm_2112031130.csv
transmission:
  widget_file_transmission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/XY Test Data
    lineEdit_sample: Test
    plainTextEdit_comments: testsinglepoint
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 200
    spinBox_integration_time_experiment: 200
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 58.0
    doubleSpinBox_y: 0.0
    spinBox_x_num: 1
    spinBox_x_off_left: 70
    spinBox_x_off_right: 10
    spinBox_y_num: 3
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 40
