decay:
  widget_digitizer_decay:
    checkBox_jitter_correction_alignment: false
    checkBox_jitter_correction_experiment: false
    comboBox_data_channel_alignment: '0'
    comboBox_data_channel_experiment: '0'
    comboBox_jitter_channel_alignment: '1'
    comboBox_jitter_channel_experiment: '1'
    comboBox_measurement_mode_alignment: single photon counting
    comboBox_measurement_mode_experiment: single photon counting
    comboBox_single_photon_compression_alignment: 50 ns
    comboBox_time_range_alignment: "640 \u03BCs"
    comboBox_time_range_experiment: "640 \u03BCs"
    spinBox_dc_offset_alignment: 9
    spinBox_dc_offset_experiment: 10
    spinBox_number_pulses_experiment: 1000
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
    spinBox_single_photon_treshold_alignment: 778
    spinBox_single_photon_treshold_experiment: 778
  widget_file_decay:
    comboBox_bandpass_filter: 640 nm -10 nm - Thorlabs FB640-10-1 V 1-39-11
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 44X44 mm (Quartz)
    lineEdit_directory: C:/Users/tud257183/Desktop/Bauke/DecayTests
    lineEdit_sample: SR10
    plainTextEdit_comments: "Temporary fixture where light if measured indepentently\
      \ from the incoming light setup. \n"
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 240
    spinBox_wavelength_start: 240
    spinBox_wavelength_step: 160
    spinBox_wavelength_stop: 400
  widget_shuttercontrol_decay:
    checkBox: true
  widget_xystage_decay:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 35.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 8
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 8
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
excitation_emission:
  widget_file_excitation_emission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: 830 nm - Newport 10CGA-830
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/Max/211216_Emission420nm_SR11
    lineEdit_sample: 'SR11 '
    plainTextEdit_comments: 'New Set-Up indirectly measuring '
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 600
    spinBox_wavelength_start: 420
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 420
  widget_powermeter_excitation_emission: {}
  widget_shuttercontrol_excitation_emission:
    checkBox: true
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 5000
    spinBox_integration_time_experiment: 5000
  widget_xystage_excitation_emission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 30.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 10
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 10
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
lineEdit_beamsplitter_calibration_file: C:/Users/tud257183/Desktop/XY Test Data/BeamSplitter_Calibrations/BSC_BS20WR_210_1_398_nm_2111291220.csv
transmission:
  widget_file_transmission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/Timo
    lineEdit_sample: TM15_infrared
    plainTextEdit_comments: ''
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 500
    spinBox_integration_time_experiment: 500
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 0.0
    doubleSpinBox_y: 0.0
    spinBox_x_num: 10
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 10
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
