decay:
  widget_digitizer_decay:
    checkBox_jitter_correction_alignment: false
    checkBox_jitter_correction_experiment: false
    comboBox_data_channel_alignment: '0'
    comboBox_data_channel_experiment: '0'
    comboBox_jitter_channel_alignment: '1'
    comboBox_jitter_channel_experiment: '1'
    comboBox_measurement_mode_alignment: averageing
    comboBox_measurement_mode_experiment: averageing
    comboBox_single_photon_compression_alignment: "5\u03BCs"
    comboBox_time_range_alignment: "160 \u03BCs"
    comboBox_time_range_experiment: "160 \u03BCs"
    spinBox_dc_offset_alignment: 10
    spinBox_dc_offset_experiment: 10
    spinBox_number_pulses_experiment: 1000
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
    spinBox_single_photon_treshold_alignment: 790
    spinBox_single_photon_treshold_experiment: 790
  widget_file_decay:
    comboBox_bandpass_filter: 660 nm - 10 nm - Thorlabs FB660-10-1 V 1-45-11
    comboBox_longpass_filter: 473 nm - Semrock BLP01-473R-25
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/Sem
    lineEdit_sample: BK7
    plainTextEdit_comments: ''
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 410
    spinBox_wavelength_start: 410
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 410
  widget_shuttercontrol_decay:
    checkBox: false
  widget_xystage_decay:
    checkBox_homed_x: false
    checkBox_homed_y: false
    doubleSpinBox_x: 40.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 10
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 10
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
excitation_emission:
  widget_file_excitation_emission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: 850 nm - Newport 10CGA-850
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/tud257183/Desktop/Sem
    lineEdit_sample: BK7
    plainTextEdit_comments: ''
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 420
    spinBox_wavelength_start: 410
    spinBox_wavelength_step: 1
    spinBox_wavelength_stop: 410
  widget_powermeter_excitation_emission: {}
  widget_shuttercontrol_excitation_emission:
    checkBox: false
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 1500
    spinBox_integration_time_experiment: 5000
  widget_xystage_excitation_emission:
    checkBox_homed_x: false
    checkBox_homed_y: false
    doubleSpinBox_x: 35.0
    doubleSpinBox_y: 110.0
    spinBox_x_num: 10
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 10
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
lineEdit_beamsplitter_calibration_file: C:/Users/tud257183/Desktop/XY Test Data/BeamSplitter_Calibrations/BSC_Quartz_210_1_600_withzeroing_nm_2112031130.csv
transmission:
  widget_file_transmission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 22X22 mm (Quartz small)
    lineEdit_directory: C:/Users/tud257183/Desktop/XY Test Data
    lineEdit_sample: Test
    plainTextEdit_comments: ''
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 500
    spinBox_integration_time_experiment: 500
  widget_xystage_transmission:
    checkBox_homed_x: false
    checkBox_homed_y: false
    doubleSpinBox_x: 58.0
    doubleSpinBox_y: 0.0
    spinBox_x_num: 2
    spinBox_x_off_left: 2
    spinBox_x_off_right: 2
    spinBox_y_num: 2
    spinBox_y_off_bottom: 2
    spinBox_y_off_top: 2
