decay:
  widget_digitizer_decay:
    checkBox_jitter_correction_alignment: false
    checkBox_jitter_correction_experiment: false
    comboBox_data_channel_alignment: '0'
    comboBox_data_channel_experiment: '0'
    comboBox_jitter_channel_alignment: '1'
    comboBox_jitter_channel_experiment: '1'
    comboBox_measurement_mode_alignment: single pulse
    comboBox_measurement_mode_experiment: averageing
    comboBox_single_photon_compression_alignment: none
    comboBox_time_range_alignment: "10 \u03BCs"
    comboBox_time_range_experiment: "320 \u03BCs"
    spinBox_dc_offset_alignment: 10
    spinBox_dc_offset_experiment: 10
    spinBox_number_pulses_experiment: 500
    spinBox_post_trigger_size_alignment: 90
    spinBox_post_trigger_size_experiment: 90
    spinBox_single_photon_treshold_alignment: 785
    spinBox_single_photon_treshold_experiment: 785
  widget_file_decay:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: 430 nm - Semrock FF01-430/LP-25
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: test
    plainTextEdit_comments: kjhkjh
  widget_laser_decay:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 375
    spinBox_wavelength_start: 350
    spinBox_wavelength_step: 25
    spinBox_wavelength_stop: 375
  widget_shuttercontrol_decay:
    checkBox: false
  widget_xystage_decay:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 70.0
    doubleSpinBox_y: 100.0
    spinBox_x_num: 2
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 2
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
excitation_emission:
  widget_file_excitation_emission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad/TestfilesXY
    lineEdit_sample: Test
    plainTextEdit_comments: Whatever
  widget_laser_excitation_emission:
    checkBox_stable: true
    comboBox_energy_level_experiment: Max
    spinBox_wavelength_alignment: 375
    spinBox_wavelength_start: 350
    spinBox_wavelength_step: 10
    spinBox_wavelength_stop: 370
  widget_powermeter_excitation_emission: {}
  widget_shuttercontrol_excitation_emission:
    checkBox: false
  widget_spectrometer_excitation_emission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 500
    spinBox_integration_time_experiment: 500
  widget_xystage_excitation_emission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 0.0
    doubleSpinBox_y: 0.0
    spinBox_x_num: 2
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 2
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
lineEdit_beamsplitter_calibration_file: C:/Users/bauke/OneDrive/Bureaublad/BeamSplitter_Calibrations/BS20WR_350_10_370_nm_2111261501.csv
transmission:
  widget_file_transmission:
    comboBox_bandpass_filter: none
    comboBox_longpass_filter: none
    comboBox_nd_filter: none
    comboBox_substrate: 50X50 mm (Borofloat)
    lineEdit_directory: C:/Users/bauke/OneDrive/Bureaublad
    lineEdit_sample: Test
    plainTextEdit_comments: Testshot
  widget_spectrometer_transmission:
    spinBox_averageing_alignment: 1
    spinBox_averageing_experiment: 1
    spinBox_integration_time_alignment: 100
    spinBox_integration_time_experiment: 500
  widget_xystage_transmission:
    checkBox_homed_x: true
    checkBox_homed_y: true
    doubleSpinBox_x: 22.0
    doubleSpinBox_y: 22.0
    spinBox_x_num: 1
    spinBox_x_off_left: 5
    spinBox_x_off_right: 5
    spinBox_y_num: 2
    spinBox_y_off_bottom: 5
    spinBox_y_off_top: 5
